// Code generated by re2c 2.2 on Tue May 23 10:23:16 2023, DO NOT EDIT.
package lexer

import (
    "bytes"
    "github.com/masp/garlang/token"
)

func (l *Lexer) lex() (pos token.Pos, tok token.Type, lit string, err error) {
    for {
		lit = ""
		pos = l.pos()
		l.token = l.cursor


{
	var yych byte
	yyaccept := 0
	yych = l.input[l.cursor]
	switch (yych) {
	case 0x00:
		goto yy2
	case '\t':
		fallthrough
	case ' ':
		goto yy6
	case '\n':
		goto yy9
	case '\r':
		goto yy11
	case '!':
		goto yy12
	case '"':
		goto yy13
	case '\'':
		goto yy15
	case '(':
		goto yy17
	case ')':
		goto yy19
	case '*':
		goto yy21
	case '+':
		goto yy23
	case ',':
		goto yy25
	case '-':
		goto yy27
	case '.':
		goto yy29
	case '/':
		goto yy31
	case '0':
		goto yy33
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		goto yy34
	case ':':
		goto yy37
	case ';':
		goto yy39
	case '<':
		goto yy41
	case '=':
		goto yy43
	case '>':
		goto yy45
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'e':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 's':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy47
	case '[':
		goto yy50
	case ']':
		goto yy52
	case '`':
		goto yy54
	case 'f':
		goto yy56
	case 'i':
		goto yy57
	case 'm':
		goto yy58
	case 'r':
		goto yy59
	case 't':
		goto yy60
	case '{':
		goto yy61
	case '}':
		goto yy63
	default:
		goto yy4
	}
yy2:
	l.cursor += 1
	{ tok = token.EOF; return }
yy4:
	l.cursor += 1
yy5:
	{ err = ErrUnrecognizedToken; return }
yy6:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == '\t') {
		goto yy6
	}
	if (yych == ' ') {
		goto yy6
	}
	{
			continue
		}
yy9:
	l.cursor += 1
	{
			if l.insertSemi() {
				l.cursor = l.token // Has the effect of "inserting" the semicolon in the input
				tok = token.Semicolon
				lit = "\n"
				return
			} else {
				l.file.AddLine(l.token)
				continue
			}
		}
yy11:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == '\n') {
		goto yy9
	}
	goto yy5
yy12:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == '=') {
		goto yy65
	}
	goto yy5
yy13:
	l.cursor += 1
	{ return l.lexString('"') }
yy15:
	l.cursor += 1
	{
            pos, tok, lit, err = l.lexString('\'')
            if tok == token.String {
                tok = token.Atom
            }
            return
        }
yy17:
	l.cursor += 1
	{ tok = token.LParen; lit = "("; return }
yy19:
	l.cursor += 1
	{ tok = token.RParen; lit = ")"; return }
yy21:
	l.cursor += 1
	{ tok = token.Star; lit = "*"; return }
yy23:
	l.cursor += 1
	{ tok = token.Plus; lit = "+"; return }
yy25:
	l.cursor += 1
	{ tok = token.Comma; lit = ","; return }
yy27:
	l.cursor += 1
	{ tok = token.Minus; lit = "-"; return }
yy29:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych <= '/') {
		goto yy30
	}
	if (yych <= '9') {
		goto yy67
	}
yy30:
	{ tok = token.Period; lit = "."; return }
yy31:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == '*') {
		goto yy70
	}
	if (yych == '/') {
		goto yy72
	}
	{ tok = token.Slash; lit = "/"; return }
yy33:
	yyaccept = 0
	l.cursor += 1
	l.marker = l.cursor
	yych = l.input[l.cursor]
	if (yych <= '9') {
		if (yych == '.') {
			goto yy67
		}
		if (yych <= '/') {
			goto yy5
		}
		goto yy75
	} else {
		if (yych <= 'E') {
			if (yych <= 'D') {
				goto yy5
			}
			goto yy78
		} else {
			if (yych == 'e') {
				goto yy78
			}
			goto yy5
		}
	}
yy34:
	yyaccept = 1
	l.cursor += 1
	l.marker = l.cursor
	yych = l.input[l.cursor]
	if (yych <= '9') {
		if (yych == '.') {
			goto yy67
		}
		if (yych >= '0') {
			goto yy34
		}
	} else {
		if (yych <= 'E') {
			if (yych >= 'E') {
				goto yy78
			}
		} else {
			if (yych == 'e') {
				goto yy78
			}
		}
	}
yy36:
	{ tok = token.Integer; lit = l.literal(); return }
yy37:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == '=') {
		goto yy79
	}
	{ tok = token.Colon; lit = ":"; return }
yy39:
	l.cursor += 1
	{ tok = token.Semicolon; lit = ";"; return }
yy41:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == '=') {
		goto yy81
	}
	{ tok = token.Less; lit = "<"; return }
yy43:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == '=') {
		goto yy83
	}
	{ tok = token.Equal; lit = "="; return }
yy45:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == '=') {
		goto yy85
	}
	{ tok = token.Greater; lit = ">"; return }
yy47:
	l.cursor += 1
	yych = l.input[l.cursor]
yy48:
	if (yych <= 'Z') {
		if (yych <= '/') {
			goto yy49
		}
		if (yych <= '9') {
			goto yy47
		}
		if (yych >= 'A') {
			goto yy47
		}
	} else {
		if (yych <= '_') {
			if (yych >= '_') {
				goto yy47
			}
		} else {
			if (yych <= '`') {
				goto yy49
			}
			if (yych <= 'z') {
				goto yy47
			}
		}
	}
yy49:
	{ tok = token.Identifier; lit = l.literal(); return }
yy50:
	l.cursor += 1
	{ tok = token.LSquareBracket; lit = "["; return }
yy52:
	l.cursor += 1
	{ tok = token.RSquareBracket; lit = "]"; return }
yy54:
	l.cursor += 1
	{ return l.lexRawString('`') }
yy56:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'u') {
		goto yy87
	}
	goto yy48
yy57:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'm') {
		goto yy88
	}
	goto yy48
yy58:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'a') {
		goto yy89
	}
	if (yych == 'o') {
		goto yy90
	}
	goto yy48
yy59:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'e') {
		goto yy91
	}
	goto yy48
yy60:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'u') {
		goto yy92
	}
	if (yych == 'y') {
		goto yy93
	}
	goto yy48
yy61:
	l.cursor += 1
	{ tok = token.LCurlyBracket; lit = "{"; return }
yy63:
	l.cursor += 1
	{ tok = token.RCurlyBracket; lit = "}"; return }
yy65:
	l.cursor += 1
	{ tok = token.BangEqual; lit = "!="; return }
yy67:
	yyaccept = 2
	l.cursor += 1
	l.marker = l.cursor
	yych = l.input[l.cursor]
	if (yych <= 'D') {
		if (yych <= '/') {
			goto yy69
		}
		if (yych <= '9') {
			goto yy67
		}
	} else {
		if (yych <= 'E') {
			goto yy78
		}
		if (yych == 'e') {
			goto yy78
		}
	}
yy69:
	{ tok = token.Float; lit = l.literal(); return }
yy70:
	yyaccept = 3
	l.cursor += 1
	l.marker = l.cursor
	yych = l.input[l.cursor]
	if (yych >= 0x01) {
		goto yy95
	}
yy71:
	{ return l.lexMultiComment() }
yy72:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych <= '\n') {
		if (yych <= 0x00) {
			goto yy74
		}
		if (yych <= '\t') {
			goto yy72
		}
	} else {
		if (yych != '\r') {
			goto yy72
		}
	}
yy74:
	{ tok = token.Comment; lit = l.literal(); return }
yy75:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych <= '9') {
		if (yych == '.') {
			goto yy67
		}
		if (yych >= '0') {
			goto yy75
		}
	} else {
		if (yych <= 'E') {
			if (yych >= 'E') {
				goto yy78
			}
		} else {
			if (yych == 'e') {
				goto yy78
			}
		}
	}
yy77:
	l.cursor = l.marker
	if (yyaccept <= 1) {
		if (yyaccept == 0) {
			goto yy5
		} else {
			goto yy36
		}
	} else {
		if (yyaccept == 2) {
			goto yy69
		} else {
			goto yy71
		}
	}
yy78:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych <= ',') {
		if (yych == '+') {
			goto yy97
		}
		goto yy77
	} else {
		if (yych <= '-') {
			goto yy97
		}
		if (yych <= '/') {
			goto yy77
		}
		if (yych <= '9') {
			goto yy98
		}
		goto yy77
	}
yy79:
	l.cursor += 1
	{ tok = token.ColonEqual; lit = ":="; return }
yy81:
	l.cursor += 1
	{ tok = token.LessEqual; lit = "<="; return }
yy83:
	l.cursor += 1
	{ tok = token.EqualEqual; lit = "=="; return }
yy85:
	l.cursor += 1
	{ tok = token.GreaterEqual; lit = ">="; return }
yy87:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'n') {
		goto yy100
	}
	goto yy48
yy88:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'p') {
		goto yy101
	}
	goto yy48
yy89:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'p') {
		goto yy102
	}
	goto yy48
yy90:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'd') {
		goto yy104
	}
	goto yy48
yy91:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 't') {
		goto yy105
	}
	goto yy48
yy92:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'p') {
		goto yy106
	}
	goto yy48
yy93:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'p') {
		goto yy107
	}
	goto yy48
yy94:
	l.cursor += 1
	yych = l.input[l.cursor]
yy95:
	if (yych <= 0x00) {
		goto yy77
	}
	if (yych != '*') {
		goto yy94
	}
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == '/') {
		goto yy108
	}
	goto yy94
yy97:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych <= '/') {
		goto yy77
	}
	if (yych >= ':') {
		goto yy77
	}
yy98:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych <= '/') {
		goto yy69
	}
	if (yych <= '9') {
		goto yy98
	}
	goto yy69
yy100:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'c') {
		goto yy110
	}
	goto yy48
yy101:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'o') {
		goto yy112
	}
	goto yy48
yy102:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych <= 'Z') {
		if (yych <= '/') {
			goto yy103
		}
		if (yych <= '9') {
			goto yy47
		}
		if (yych >= 'A') {
			goto yy47
		}
	} else {
		if (yych <= '_') {
			if (yych >= '_') {
				goto yy47
			}
		} else {
			if (yych <= '`') {
				goto yy103
			}
			if (yych <= 'z') {
				goto yy47
			}
		}
	}
yy103:
	{ tok = token.Map; lit = "map"; return }
yy104:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'u') {
		goto yy113
	}
	goto yy48
yy105:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'u') {
		goto yy114
	}
	goto yy48
yy106:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'l') {
		goto yy115
	}
	goto yy48
yy107:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'e') {
		goto yy116
	}
	goto yy48
yy108:
	l.cursor += 1
	{ tok = token.Comment; lit = l.literal(); return }
yy110:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych <= 'Z') {
		if (yych <= '/') {
			goto yy111
		}
		if (yych <= '9') {
			goto yy47
		}
		if (yych >= 'A') {
			goto yy47
		}
	} else {
		if (yych <= '_') {
			if (yych >= '_') {
				goto yy47
			}
		} else {
			if (yych <= '`') {
				goto yy111
			}
			if (yych <= 'z') {
				goto yy47
			}
		}
	}
yy111:
	{ tok = token.Func; lit = "func"; return }
yy112:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'r') {
		goto yy118
	}
	goto yy48
yy113:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'l') {
		goto yy119
	}
	goto yy48
yy114:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'r') {
		goto yy120
	}
	goto yy48
yy115:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'e') {
		goto yy121
	}
	goto yy48
yy116:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych <= 'Z') {
		if (yych <= '/') {
			goto yy117
		}
		if (yych <= '9') {
			goto yy47
		}
		if (yych >= 'A') {
			goto yy47
		}
	} else {
		if (yych <= '_') {
			if (yych >= '_') {
				goto yy47
			}
		} else {
			if (yych <= '`') {
				goto yy117
			}
			if (yych <= 'z') {
				goto yy47
			}
		}
	}
yy117:
	{ tok = token.TypeKeyword; lit = "type"; return }
yy118:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 't') {
		goto yy123
	}
	goto yy48
yy119:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'e') {
		goto yy125
	}
	goto yy48
yy120:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'n') {
		goto yy127
	}
	goto yy48
yy121:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych <= 'Z') {
		if (yych <= '/') {
			goto yy122
		}
		if (yych <= '9') {
			goto yy47
		}
		if (yych >= 'A') {
			goto yy47
		}
	} else {
		if (yych <= '_') {
			if (yych >= '_') {
				goto yy47
			}
		} else {
			if (yych <= '`') {
				goto yy122
			}
			if (yych <= 'z') {
				goto yy47
			}
		}
	}
yy122:
	{ tok = token.Tuple; lit = "tuple"; return }
yy123:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych <= 'Z') {
		if (yych <= '/') {
			goto yy124
		}
		if (yych <= '9') {
			goto yy47
		}
		if (yych >= 'A') {
			goto yy47
		}
	} else {
		if (yych <= '_') {
			if (yych >= '_') {
				goto yy47
			}
		} else {
			if (yych <= '`') {
				goto yy124
			}
			if (yych <= 'z') {
				goto yy47
			}
		}
	}
yy124:
	{ tok = token.Import; lit = "import"; return }
yy125:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych <= 'Z') {
		if (yych <= '/') {
			goto yy126
		}
		if (yych <= '9') {
			goto yy47
		}
		if (yych >= 'A') {
			goto yy47
		}
	} else {
		if (yych <= '_') {
			if (yych >= '_') {
				goto yy47
			}
		} else {
			if (yych <= '`') {
				goto yy126
			}
			if (yych <= 'z') {
				goto yy47
			}
		}
	}
yy126:
	{ tok = token.Module; lit = "module"; return }
yy127:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych <= 'Z') {
		if (yych <= '/') {
			goto yy128
		}
		if (yych <= '9') {
			goto yy47
		}
		if (yych >= 'A') {
			goto yy47
		}
	} else {
		if (yych <= '_') {
			if (yych >= '_') {
				goto yy47
			}
		} else {
			if (yych <= '`') {
				goto yy128
			}
			if (yych <= 'z') {
				goto yy47
			}
		}
	}
yy128:
	{ tok = token.Return; lit = "return"; return }
}

    }
}

func (l *Lexer) lexString(quote byte) (pos token.Pos, tok token.Type, lit string, err error) {
	var buf bytes.Buffer
	for {
		var u byte

{
	var yych byte
	yych = l.input[l.cursor]
	if (yych <= '\n') {
		if (yych <= 0x00) {
			goto yy131
		}
		if (yych <= '\t') {
			goto yy133
		}
		goto yy135
	} else {
		if (yych == '\\') {
			goto yy137
		}
		goto yy133
	}
yy131:
	l.cursor += 1
	{
			err = ErrUnterminatedString
			tok = token.EOF
            pos = l.file.Pos(l.token)
			return
		}
yy133:
	l.cursor += 1
	{
			u = yych
			if u == quote {
				tok = token.String
				pos = l.file.Pos(l.token)
				lit = string(buf.Bytes())
				return
			}
			buf.WriteByte(u)
			continue
		}
yy135:
	l.cursor += 1
yy136:
	{ err = ErrInvalidString; return }
yy137:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych <= 'b') {
		if (yych <= '>') {
			if (yych <= '"') {
				if (yych <= '!') {
					goto yy136
				}
			} else {
				if (yych == '\'') {
					goto yy140
				}
				goto yy136
			}
		} else {
			if (yych <= '\\') {
				if (yych <= '?') {
					goto yy142
				}
				if (yych <= '[') {
					goto yy136
				}
				goto yy144
			} else {
				if (yych <= '`') {
					goto yy136
				}
				if (yych <= 'a') {
					goto yy146
				}
				goto yy148
			}
		}
	} else {
		if (yych <= 'q') {
			if (yych <= 'f') {
				if (yych <= 'e') {
					goto yy136
				}
				goto yy150
			} else {
				if (yych == 'n') {
					goto yy152
				}
				goto yy136
			}
		} else {
			if (yych <= 't') {
				if (yych <= 'r') {
					goto yy154
				}
				if (yych <= 's') {
					goto yy136
				}
				goto yy156
			} else {
				if (yych == 'v') {
					goto yy158
				}
				goto yy136
			}
		}
	}
	l.cursor += 1
	{ buf.WriteByte('"'); continue }
yy140:
	l.cursor += 1
	{ buf.WriteByte('\''); continue }
yy142:
	l.cursor += 1
	{ buf.WriteByte('?'); continue }
yy144:
	l.cursor += 1
	{ buf.WriteByte('\\'); continue }
yy146:
	l.cursor += 1
	{ buf.WriteByte('\a'); continue }
yy148:
	l.cursor += 1
	{ buf.WriteByte('\b'); continue }
yy150:
	l.cursor += 1
	{ buf.WriteByte('\f'); continue }
yy152:
	l.cursor += 1
	{ buf.WriteByte('\n'); continue }
yy154:
	l.cursor += 1
	{ buf.WriteByte('\r'); continue }
yy156:
	l.cursor += 1
	{ buf.WriteByte('\t'); continue }
yy158:
	l.cursor += 1
	{ buf.WriteByte('\v'); continue }
}
		
	}
}

func (l *Lexer) lexRawString(quote byte) (pos token.Pos, tok token.Type, lit string, err error) {
	for {

{
	var yych byte
	yych = l.input[l.cursor]
	if (yych >= 0x01) {
		goto yy164
	}
	l.cursor += 1
	{
			err = ErrUnterminatedString
			tok = token.EOF
            pos = l.file.Pos(l.token)
			return
		}
yy164:
	l.cursor += 1
	{
			if yych == quote {
				tok = token.String
				pos = l.file.Pos(l.token)
				lit = string(l.input[l.token+1:l.cursor-1])
				return
			}
			continue
		}
}
		
	}
}

func (l *Lexer) lexMultiComment() (pos token.Pos, tok token.Type, lit string, err error) {
	for {

{
	var yych byte
	yych = l.input[l.cursor]
	if (yych <= 0x00) {
		goto yy168
	}
	if (yych == '*') {
		goto yy172
	}
	goto yy170
yy168:
	l.cursor += 1
	{
			err = ErrUnterminatedComment
			tok = token.EOF
            pos = l.file.Pos(l.token)
			return
		}
yy170:
	l.cursor += 1
yy171:
	{ continue }
yy172:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych != '/') {
		goto yy171
	}
	l.cursor += 1
	{
			tok = token.Comment
			pos = l.file.Pos(l.token)
			lit = string(l.input[l.token+2:l.cursor])
			return
		}
}
		
	}
}