// Code generated by re2c 2.2 on Mon Apr 24 21:38:44 2023, DO NOT EDIT.
package lexer

import (
    "bytes"
    "github.com/masp/garlang/token"
)

func (l *Lexer) lex() (pos token.Pos, tok token.Type, lit string, err error) {
    for {
		lit = ""
		pos = l.pos()
		l.token = l.cursor


{
	var yych byte
	yyaccept := 0
	yych = l.input[l.cursor]
	switch (yych) {
	case 0x00:
		goto yy2
	case '\t':
		fallthrough
	case ' ':
		goto yy6
	case '\n':
		goto yy9
	case '\r':
		goto yy11
	case '!':
		goto yy12
	case '"':
		goto yy13
	case '\'':
		goto yy15
	case '(':
		goto yy17
	case ')':
		goto yy19
	case '*':
		goto yy21
	case '+':
		goto yy23
	case ',':
		goto yy25
	case '-':
		goto yy27
	case '.':
		goto yy29
	case '/':
		goto yy31
	case '0':
		goto yy33
	case '1':
		fallthrough
	case '2':
		fallthrough
	case '3':
		fallthrough
	case '4':
		fallthrough
	case '5':
		fallthrough
	case '6':
		fallthrough
	case '7':
		fallthrough
	case '8':
		fallthrough
	case '9':
		goto yy34
	case ':':
		goto yy37
	case ';':
		goto yy38
	case '<':
		goto yy40
	case '=':
		goto yy42
	case '>':
		goto yy44
	case 'A':
		fallthrough
	case 'B':
		fallthrough
	case 'C':
		fallthrough
	case 'D':
		fallthrough
	case 'E':
		fallthrough
	case 'F':
		fallthrough
	case 'G':
		fallthrough
	case 'H':
		fallthrough
	case 'I':
		fallthrough
	case 'J':
		fallthrough
	case 'K':
		fallthrough
	case 'L':
		fallthrough
	case 'M':
		fallthrough
	case 'N':
		fallthrough
	case 'O':
		fallthrough
	case 'P':
		fallthrough
	case 'Q':
		fallthrough
	case 'R':
		fallthrough
	case 'S':
		fallthrough
	case 'T':
		fallthrough
	case 'U':
		fallthrough
	case 'V':
		fallthrough
	case 'W':
		fallthrough
	case 'X':
		fallthrough
	case 'Y':
		fallthrough
	case 'Z':
		fallthrough
	case '_':
		fallthrough
	case 'a':
		fallthrough
	case 'b':
		fallthrough
	case 'c':
		fallthrough
	case 'd':
		fallthrough
	case 'g':
		fallthrough
	case 'h':
		fallthrough
	case 'i':
		fallthrough
	case 'j':
		fallthrough
	case 'k':
		fallthrough
	case 'l':
		fallthrough
	case 'n':
		fallthrough
	case 'o':
		fallthrough
	case 'p':
		fallthrough
	case 'q':
		fallthrough
	case 's':
		fallthrough
	case 't':
		fallthrough
	case 'u':
		fallthrough
	case 'v':
		fallthrough
	case 'w':
		fallthrough
	case 'x':
		fallthrough
	case 'y':
		fallthrough
	case 'z':
		goto yy46
	case '`':
		goto yy49
	case 'e':
		goto yy51
	case 'f':
		goto yy52
	case 'm':
		goto yy53
	case 'r':
		goto yy54
	case '{':
		goto yy55
	case '}':
		goto yy57
	default:
		goto yy4
	}
yy2:
	l.cursor += 1
	{ tok = token.EOF; return }
yy4:
	l.cursor += 1
yy5:
	{ err = ErrUnrecognizedToken; return }
yy6:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == '\t') {
		goto yy6
	}
	if (yych == ' ') {
		goto yy6
	}
	{
			continue
		}
yy9:
	l.cursor += 1
	{
			if l.insertSemi() {
				l.cursor = l.token // Has the effect of "inserting" the semicolon in the input
				tok = token.Semicolon
				lit = "\n"
				return
			} else {
				l.file.AddLine(l.token)
				continue
			}
		}
yy11:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == '\n') {
		goto yy9
	}
	goto yy5
yy12:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == '=') {
		goto yy59
	}
	goto yy5
yy13:
	l.cursor += 1
	{ return l.lexString('"') }
yy15:
	l.cursor += 1
	{
            pos, tok, lit, err = l.lexString('\'')
            if tok == token.String {
                tok = token.Atom
            }
            return
        }
yy17:
	l.cursor += 1
	{ tok = token.LeftParen; lit = "("; return }
yy19:
	l.cursor += 1
	{ tok = token.RightParen; lit = ")"; return }
yy21:
	l.cursor += 1
	{ tok = token.Star; lit = "*"; return }
yy23:
	l.cursor += 1
	{ tok = token.Plus; lit = "+"; return }
yy25:
	l.cursor += 1
	{ tok = token.Comma; lit = ","; return }
yy27:
	l.cursor += 1
	{ tok = token.Minus; lit = "-"; return }
yy29:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych <= '/') {
		goto yy30
	}
	if (yych <= '9') {
		goto yy61
	}
yy30:
	{ tok = token.Period; lit = "."; return }
yy31:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == '/') {
		goto yy64
	}
	{ tok = token.Slash; lit = "/"; return }
yy33:
	yyaccept = 0
	l.cursor += 1
	l.marker = l.cursor
	yych = l.input[l.cursor]
	if (yych <= '9') {
		if (yych == '.') {
			goto yy61
		}
		if (yych <= '/') {
			goto yy5
		}
		goto yy67
	} else {
		if (yych <= 'E') {
			if (yych <= 'D') {
				goto yy5
			}
			goto yy70
		} else {
			if (yych == 'e') {
				goto yy70
			}
			goto yy5
		}
	}
yy34:
	yyaccept = 1
	l.cursor += 1
	l.marker = l.cursor
	yych = l.input[l.cursor]
	if (yych <= '9') {
		if (yych == '.') {
			goto yy61
		}
		if (yych >= '0') {
			goto yy34
		}
	} else {
		if (yych <= 'E') {
			if (yych >= 'E') {
				goto yy70
			}
		} else {
			if (yych == 'e') {
				goto yy70
			}
		}
	}
yy36:
	{ tok = token.Integer; lit = l.literal(); return }
yy37:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == '=') {
		goto yy71
	}
	goto yy5
yy38:
	l.cursor += 1
	{ tok = token.Semicolon; lit = ";"; return }
yy40:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == '=') {
		goto yy73
	}
	{ tok = token.Less; lit = "<"; return }
yy42:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == '=') {
		goto yy75
	}
	{ tok = token.Equal; lit = "="; return }
yy44:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == '=') {
		goto yy77
	}
	{ tok = token.Greater; lit = ">"; return }
yy46:
	l.cursor += 1
	yych = l.input[l.cursor]
yy47:
	if (yych <= 'Z') {
		if (yych <= '/') {
			goto yy48
		}
		if (yych <= '9') {
			goto yy46
		}
		if (yych >= 'A') {
			goto yy46
		}
	} else {
		if (yych <= '_') {
			if (yych >= '_') {
				goto yy46
			}
		} else {
			if (yych <= '`') {
				goto yy48
			}
			if (yych <= 'z') {
				goto yy46
			}
		}
	}
yy48:
	{ tok = token.Identifier; lit = l.literal(); return }
yy49:
	l.cursor += 1
	{ return l.lexRawString('`') }
yy51:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'x') {
		goto yy79
	}
	goto yy47
yy52:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'u') {
		goto yy80
	}
	goto yy47
yy53:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'o') {
		goto yy81
	}
	goto yy47
yy54:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'e') {
		goto yy82
	}
	goto yy47
yy55:
	l.cursor += 1
	{ tok = token.LeftBrace; lit = "{"; return }
yy57:
	l.cursor += 1
	{ tok = token.RightBrace; lit = "}"; return }
yy59:
	l.cursor += 1
	{ tok = token.BangEqual; lit = "!="; return }
yy61:
	yyaccept = 2
	l.cursor += 1
	l.marker = l.cursor
	yych = l.input[l.cursor]
	if (yych <= 'D') {
		if (yych <= '/') {
			goto yy63
		}
		if (yych <= '9') {
			goto yy61
		}
	} else {
		if (yych <= 'E') {
			goto yy70
		}
		if (yych == 'e') {
			goto yy70
		}
	}
yy63:
	{ tok = token.Float; lit = l.literal(); return }
yy64:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych <= '\n') {
		if (yych <= 0x00) {
			goto yy66
		}
		if (yych <= '\t') {
			goto yy64
		}
	} else {
		if (yych != '\r') {
			goto yy64
		}
	}
yy66:
	{ tok = token.Comment; lit = l.literal(); return }
yy67:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych <= '9') {
		if (yych == '.') {
			goto yy61
		}
		if (yych >= '0') {
			goto yy67
		}
	} else {
		if (yych <= 'E') {
			if (yych >= 'E') {
				goto yy70
			}
		} else {
			if (yych == 'e') {
				goto yy70
			}
		}
	}
yy69:
	l.cursor = l.marker
	if (yyaccept <= 1) {
		if (yyaccept == 0) {
			goto yy5
		} else {
			goto yy36
		}
	} else {
		goto yy63
	}
yy70:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych <= ',') {
		if (yych == '+') {
			goto yy83
		}
		goto yy69
	} else {
		if (yych <= '-') {
			goto yy83
		}
		if (yych <= '/') {
			goto yy69
		}
		if (yych <= '9') {
			goto yy84
		}
		goto yy69
	}
yy71:
	l.cursor += 1
	{ tok = token.ColonEqual; lit = ":="; return }
yy73:
	l.cursor += 1
	{ tok = token.LessEqual; lit = "<="; return }
yy75:
	l.cursor += 1
	{ tok = token.EqualEqual; lit = "=="; return }
yy77:
	l.cursor += 1
	{ tok = token.GreaterEqual; lit = ">="; return }
yy79:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'p') {
		goto yy86
	}
	goto yy47
yy80:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'n') {
		goto yy87
	}
	goto yy47
yy81:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'd') {
		goto yy88
	}
	goto yy47
yy82:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 't') {
		goto yy89
	}
	goto yy47
yy83:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych <= '/') {
		goto yy69
	}
	if (yych >= ':') {
		goto yy69
	}
yy84:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych <= '/') {
		goto yy63
	}
	if (yych <= '9') {
		goto yy84
	}
	goto yy63
yy86:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'o') {
		goto yy90
	}
	goto yy47
yy87:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'c') {
		goto yy91
	}
	goto yy47
yy88:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'u') {
		goto yy93
	}
	goto yy47
yy89:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'u') {
		goto yy94
	}
	goto yy47
yy90:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'r') {
		goto yy95
	}
	goto yy47
yy91:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych <= 'Z') {
		if (yych <= '/') {
			goto yy92
		}
		if (yych <= '9') {
			goto yy46
		}
		if (yych >= 'A') {
			goto yy46
		}
	} else {
		if (yych <= '_') {
			if (yych >= '_') {
				goto yy46
			}
		} else {
			if (yych <= '`') {
				goto yy92
			}
			if (yych <= 'z') {
				goto yy46
			}
		}
	}
yy92:
	{ tok = token.Func; lit = "func"; return }
yy93:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'l') {
		goto yy96
	}
	goto yy47
yy94:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'r') {
		goto yy97
	}
	goto yy47
yy95:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 't') {
		goto yy98
	}
	goto yy47
yy96:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'e') {
		goto yy100
	}
	goto yy47
yy97:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych == 'n') {
		goto yy102
	}
	goto yy47
yy98:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych <= 'Z') {
		if (yych <= '/') {
			goto yy99
		}
		if (yych <= '9') {
			goto yy46
		}
		if (yych >= 'A') {
			goto yy46
		}
	} else {
		if (yych <= '_') {
			if (yych >= '_') {
				goto yy46
			}
		} else {
			if (yych <= '`') {
				goto yy99
			}
			if (yych <= 'z') {
				goto yy46
			}
		}
	}
yy99:
	{ tok = token.Export; lit = "export"; return }
yy100:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych <= 'Z') {
		if (yych <= '/') {
			goto yy101
		}
		if (yych <= '9') {
			goto yy46
		}
		if (yych >= 'A') {
			goto yy46
		}
	} else {
		if (yych <= '_') {
			if (yych >= '_') {
				goto yy46
			}
		} else {
			if (yych <= '`') {
				goto yy101
			}
			if (yych <= 'z') {
				goto yy46
			}
		}
	}
yy101:
	{ tok = token.Module; lit = "module"; return }
yy102:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych <= 'Z') {
		if (yych <= '/') {
			goto yy103
		}
		if (yych <= '9') {
			goto yy46
		}
		if (yych >= 'A') {
			goto yy46
		}
	} else {
		if (yych <= '_') {
			if (yych >= '_') {
				goto yy46
			}
		} else {
			if (yych <= '`') {
				goto yy103
			}
			if (yych <= 'z') {
				goto yy46
			}
		}
	}
yy103:
	{ tok = token.Return; lit = "return"; return }
}

    }
}

func (l *Lexer) lexString(quote byte) (pos token.Pos, tok token.Type, lit string, err error) {
	var buf bytes.Buffer
	for {
		var u byte

{
	var yych byte
	yych = l.input[l.cursor]
	if (yych <= '\n') {
		if (yych <= 0x00) {
			goto yy106
		}
		if (yych <= '\t') {
			goto yy108
		}
		goto yy110
	} else {
		if (yych == '\\') {
			goto yy112
		}
		goto yy108
	}
yy106:
	l.cursor += 1
	{
			err = ErrUnterminatedString
			tok = token.EOF
            pos = l.file.Pos(l.token)
			return
		}
yy108:
	l.cursor += 1
	{
			u = yych
			if u == quote {
				tok = token.String
				pos = l.file.Pos(l.token)
				lit = string(buf.Bytes())
				return
			}
			buf.WriteByte(u)
			continue
		}
yy110:
	l.cursor += 1
yy111:
	{ err = ErrInvalidString; return }
yy112:
	l.cursor += 1
	yych = l.input[l.cursor]
	if (yych <= 'b') {
		if (yych <= '>') {
			if (yych <= '"') {
				if (yych <= '!') {
					goto yy111
				}
			} else {
				if (yych == '\'') {
					goto yy115
				}
				goto yy111
			}
		} else {
			if (yych <= '\\') {
				if (yych <= '?') {
					goto yy117
				}
				if (yych <= '[') {
					goto yy111
				}
				goto yy119
			} else {
				if (yych <= '`') {
					goto yy111
				}
				if (yych <= 'a') {
					goto yy121
				}
				goto yy123
			}
		}
	} else {
		if (yych <= 'q') {
			if (yych <= 'f') {
				if (yych <= 'e') {
					goto yy111
				}
				goto yy125
			} else {
				if (yych == 'n') {
					goto yy127
				}
				goto yy111
			}
		} else {
			if (yych <= 't') {
				if (yych <= 'r') {
					goto yy129
				}
				if (yych <= 's') {
					goto yy111
				}
				goto yy131
			} else {
				if (yych == 'v') {
					goto yy133
				}
				goto yy111
			}
		}
	}
	l.cursor += 1
	{ buf.WriteByte('"'); continue }
yy115:
	l.cursor += 1
	{ buf.WriteByte('\''); continue }
yy117:
	l.cursor += 1
	{ buf.WriteByte('?'); continue }
yy119:
	l.cursor += 1
	{ buf.WriteByte('\\'); continue }
yy121:
	l.cursor += 1
	{ buf.WriteByte('\a'); continue }
yy123:
	l.cursor += 1
	{ buf.WriteByte('\b'); continue }
yy125:
	l.cursor += 1
	{ buf.WriteByte('\f'); continue }
yy127:
	l.cursor += 1
	{ buf.WriteByte('\n'); continue }
yy129:
	l.cursor += 1
	{ buf.WriteByte('\r'); continue }
yy131:
	l.cursor += 1
	{ buf.WriteByte('\t'); continue }
yy133:
	l.cursor += 1
	{ buf.WriteByte('\v'); continue }
}
		
	}
}

func (l *Lexer) lexRawString(quote byte) (pos token.Pos, tok token.Type, lit string, err error) {
	for {

{
	var yych byte
	yych = l.input[l.cursor]
	if (yych >= 0x01) {
		goto yy139
	}
	l.cursor += 1
	{
			err = ErrUnterminatedString
			tok = token.EOF
            pos = l.file.Pos(l.token)
			return
		}
yy139:
	l.cursor += 1
	{
			if yych == quote {
				tok = token.String
				pos = l.file.Pos(l.token)
				lit = string(l.input[l.token+1:l.cursor-1])
				return
			}
			continue
		}
}
		
	}
}